### ISSUE TITLE
Problem with getting started instructions

### ISSUE THREAD

**Issue by bostonou** [xmrit/xmrit#12]
Following the [Getting Started instructions](https://github.com/xmrit/xmrit?tab=readme-ov-file#getting-started) gives an error when loading the site. The error seems to change based on the http server. Running `ruby -run -e httpd . -p 5000` from the root dir results in an error loading `main2.ts`:

> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.

Tested this with v1.1.0 and v1.0.0.

**Comment by LukasMurdock** [comment]
Seems the latest release `.zip` isn’t the built version of the site.

@bostonou If you have Node/NPM installed, you can run `npm install` and then `npm run build` to get a static `/dist` directory to start a http server on. Alternatively, after `npm install`, you can run `npm run start` to start the Parcel dev server.

**Comment by benclmnt** [comment]
Yup, i will need to change the getting started instructions. Thanks @LukasMurdock
