### ISSUE TITLE
Slash Date Formatting Results in Strange Plotting Order

### ISSUE THREAD

**Issue by sharedphysics** [xmrit/xmrit#13]
While instructions are to use dash style dates (`YYYY-MM-DD`), they also say we can use other dates and XMRIT will try to format correctly. On using `MM/DD/YY` formatted dates, the line plotting went sideways. The days plotted are correct, but the line is not.

![image](https://github.com/user-attachments/assets/c8197568-852b-4cd0-909b-4dd3f09e0a4f)

Interestingly, if I removed some of the initial values to highlight just the broken dates and chart side by side, the chart seemed to resolve itself correctly.

**Comment by LukasMurdock** [comment]
@sharedphysics If you hit the `Refresh Charts` button in the top left does the chart resolve itself correctly?

I am able to replicate this by thrashing the date values around. Hitting Refresh Charts seems to fix though.

**Comment by benclmnt** [comment]
Thanks for reporting this bug, we have a fix in place
