### ISSUE TITLE
xmrit-logo.png not included

### ISSUE THREAD

**Issue by LukasMurdock** [xmrit/xmrit#3]
The `xmrit-logo.png` file referenced in `css/styles.css` is not included in the repo currently.

https://github.com/xmrit/xmrit/blob/951a9c215c1f2d0bd3ced08401b0a92c9e832957/css/styles.css#L1745

**Comment by ejamesc** [comment]
Good catch! cc'ing @benclmnt — should be a simple modification to our open source script, yes?
